name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: MELCloud Coordinator release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: "Set version number"
        run: |
          yq -i -o json '.version="${{ github.event.release.tag_name }}"' \
            "${{ github.workspace }}/custom_components/melcloud/manifest.json"

      # Pack the HACS dir as a zip and upload to the release
      - name: ZIP MELCloud Dir
        run: |
          cd "${{ github.workspace }}/custom_components/melcloud"
          zip melcloud.zip -r ./

      - name: Upload zip to release
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: ${{ github.workspace }}/custom_components/melcloud/melcloud.zip
